name: Docker Build and Push  

on:  
  push:  
    branches: [ main ]  
  workflow_dispatch:  # 允许手动触发  

# 添加这个权限配置  
permissions:  
  contents: read  
  packages: write  # 这是关键，使 GITHUB_TOKEN 有权限推送到 GHCR  

jobs:  
  build:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v3  

      - name: Set up Docker Buildx  
        uses: docker/setup-buildx-action@v2  

      - name: Login to GitHub Container Registry  
        uses: docker/login-action@v2  
        with:  
          registry: ghcr.io  
          username: ${{ github.repository_owner }}  
          password: ${{ secrets.GITHUB_TOKEN }}  

      - name: Build and push  
        uses: docker/build-push-action@v4  
        with:  
          context: .  
          push: true  
          tags: ghcr.io/hanzshaoui/duanju:latest  
